#
# Copyright 2019 ForgeRock AS. All Rights Reserved
#

# https://stash.forgerock.org/projects/CLOUD/repos/forgeops/browse/docker/java-11/Dockerfile
FROM gcr.io/forgerock-io/java-11:latest

# tini avoids zombie processes and helps signal propagation
ADD https://github.com/krallin/tini/releases/download/v0.18.0/tini /usr/bin/tini

# Try to keep all RUN operations in one place to reduce Docker layer creation
# - ttf-dejavu font needed by Activiti workflow
# - make tini executable
RUN apt-get update && \
    apt-get install -y ttf-dejavu && \
    chmod +x /usr/bin/tini

# copy IDM files, and remove /samples directory
COPY --chown=forgerock:root build/resources/openidm /opt/
RUN rm -fr /opt/openidm/samples

WORKDIR /opt/openidm

EXPOSE 8080

USER 11111

ENTRYPOINT ["/usr/bin/tini", "--"]

CMD ["/opt/openidm/bin/docker-entrypoint.sh", "openidm"]